server:
  port: 10000
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/trip_plan
    username: tripplan
    password: 1234
    driver-class-name: org.postgresql.Driver


  jpa:
    open-in-view: true
    #jpa format
    properties:
      hibernate:
        format_sql: true
        show_sql: true
        highlight_sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    database-platform: org.hibernate.spatial.dialect.postgis.PostgisPG95Dialect